version: '3.8'

services:
  web:
    image: nginx
    ports:
      - "8080:80"
    networks:
      - my_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
